apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: databases
data:
  init-dbs-and-tables.sql: |
    CREATE DATABASE EbayEmail;
    USE EbayMail;
    CREATE TABLE US (
        id INT AUTO_INCREMENT PRIMARY KEY,
        email VARCHAR(100)
    );

    CREATE TABLE INTER (
        id INT AUTO_INCREMENT PRIMARY KEY,
        email VARCHAR(100),
        geo VARCHAR(100)
    );

    CREATE DATABASE PoshmarkEmail;
    USE PoshmarkEmail;
    CREATE TABLE Total (
        id INT AUTO_INCREMENT PRIMARY KEY,
        email VARCHAR(100)
    );
---
apiVersion: v1
kind: Namespace
metadata:
  name:  databases
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: databases
type: kubernetes.io/basic-auth
stringData:
  password: root
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: databases
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: databases
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: databases
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init-dbs-and-tables.sql
          subPath: init-dbs-and-tables.sql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: init-script
        configMap:
          name: mysql-init-script
---
apiVersion: v1
kind: Service
metadata:
  namespace: databases
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql